name: Pull Request Checks

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Check Formatting & Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run cargo test
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    name: Runs Cargo Clippy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --workspace --tests -- --warn clippy::all --warn clippy::nursery
